name: Test Login Action for Login Issue 464
on:
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0E7D9513B6144F44A1298EC33518C78A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E7A9F92BD90648C195CF8C2F6F50CA42 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5C8AA0BFC20B4527BA6F36B219868C56 }}
